name: face_recogination_flutter_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  permission_handler: ^12.0.1
  image: ^4.5.4
  shared_preferences: ^2.5.3
  http: ^1.4.0
  js: ^0.7.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
